ChartValues:
  images:
    registry: compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/public
  dashboard:
    persistentVolume:
      size: 40Gi
      storageClassName: alicloud-disk-essd
    service:
      type: LoadBalancer
HelmChartPath: helm/chaos-mesh
RuntimeType: Kubernetes
OutputCmd: |-
  export SERVICE_IP=$(kubectl get svc chaos-dashboard -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
  echo "Visit URL: http://$SERVICE_IP:2333"
ServiceType: private
ArtifactSourceType: HelmChart
ServiceBuildRegion: ap-southeast-1
RepoName: aliyun-computenest/quickstart-ChaosMesh
RegionId: cn-hangzhou
OutputType: OutputCommand
Owner: JJGGu
Branch: main
Platform: github
